# Generated by Django 5.2.6 on 2026-02-25 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CachedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=300)),
                ('openlibrary_id', models.CharField(blank=True, max_length=200)),
                ('inventaire_uri', models.CharField(blank=True, max_length=200)),
                ('cover_url', models.URLField(blank=True, max_length=1000)),
                ('subjects', models.JSONField(default=list)),
                ('award_slugs', models.JSONField(default=list)),
                ('description', models.TextField(blank=True)),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('publisher', models.CharField(blank=True, max_length=300)),
                ('published_date', models.CharField(blank=True, max_length=20)),
                ('first_publish_year', models.IntegerField(blank=True, null=True)),
                ('isbn_13', models.CharField(blank=True, max_length=13)),
                ('isbn_10', models.CharField(blank=True, max_length=10)),
                ('language', models.CharField(blank=True, max_length=10)),
                ('ol_ratings_average', models.FloatField(blank=True, null=True)),
                ('ol_ratings_count', models.IntegerField(blank=True, null=True)),
                ('want_to_read_count', models.IntegerField(blank=True, null=True)),
                ('openlibrary_fetched', models.BooleanField(default=False)),
                ('inventaire_fetched', models.BooleanField(default=False)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['title', 'author'], name='books_cache_title_e6595c_idx')],
                'unique_together': {('title', 'author')},
            },
        ),
    ]
